version: '3'
services:
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongodb
    entrypoint: ["/usr/bin/mongod","--bind_ip_all","--replSet","rs0"]
    ports:
      - "27017:27017"
  mongosetup:
    image: mongo
    depends_on:
      - mongo
    restart: "no"
    entrypoint: [ "bash", "-c", "sleep 10 && mongo --host mongo:27017 --eval 'rs.initiate()'"]
  api:
    container_name: app
    build: .
    restart: always
    depends_on:
      - mongosetup
    ports:
      - "8080:8080"